<a class="navbar-brand" data-toggle="modal" href="#myModal">Вход</a>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Авторизационная форма</h4>
            </div>
            <form method="post" action="//Localhost/Blog_Anna_molibog/index.php">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Login</label>
                        <input name="user_login" type="text" class="form-control" id="exampleInputEmail1" placeholder="Login">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input name="user_password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" name="submit">Войти</button>
                </div>
            </form>
        </div>
    </div>
</div>