<a class="navbar-brand" data-toggle="modal" href="#myModal"><button type="button" class="btn btn-success btn-sm btn-block">Добавить новый пост</button></a>
<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Добавить новый пост</h4>
            </div>
            <form method="post" action="//Localhost/Blog_Anna_molibog/admin.php">
                <div class="modal-body">
                    <div class="form-group">
                        <label>Название</label>
                        <input name="title" type="text" class="form-control" placeholder="Title">
                    </div>
                    <div class="form-group">
                        <label>Дата</label>
                        <input name="date" type="datetime" class="form-control" placeholder="0000-00-00 00-00-00">
                    </div>
                    <div class="form-group">
                        <label>Содержимое статьи</label>
                        <textarea rows="30" cols="120" class="form-control" name="content" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Изображение</label>
                        <input name="image" type="text" class="form-control" placeholder="Image_name.jpg">
                    </div>
                    <div class="form-group">
                        <select class="form-control" name="id_category">
                            <?php foreach($categories as $category) { ?>
                            <option value="<?=$category['id_category']?>"><?=$category['category']?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Теги</label>
                        <input name="tag" type="text" class="form-control" placeholder="#tag">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary" name="add">Добавить</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </form>
        </div>
    </div>
</div>