<?php
include "partials/header.phtml";
?>
    <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="list-group">
            <a href="//Localhost/Blog_Anna_Molibog/index.php" class="list-group-item">Все статьи</a>
            <?php foreach ($categories as $category) { ?>
                <a href="//Localhost/Blog_Anna_Molibog/index.php?id_category=<?=$category['id_category']?>" class="list-group-item"><?=$category['category']?></a>
            <?php } ?>
        </div>
    </div>

        <div class="col-lg-9 col-md-9 col-sm-9">
            <img style="float: right" class="img-rounded" width="250" height="250" src="//Localhost/Blog_Anna_Molibog/uploads/<?=$currentArticle[0]['image']?>">

            <h3><a href = "//Localhost/Blog_Anna_Molibog/article.php?id=<?=$currentArticle['id']?>"><?=$currentArticle[0]['title']?></a></h3>
            <em><?=$currentArticle[0]['date']?></em>
            <p><?=$currentArticle[0]['content'];?></p>

        </div>

</div>
<?php
include "partials/footer.phtml";
?>