

        <form method="post" action="//Localhost/Blog_Anna_Molibog/admin.php">
            <div class="modal-body">
                <div class="form-group">
                    <input name="id" type="hidden" class="form-control" placeholder="Title" value="<?=$currentArticle[0]['id']?>">
                </div>
                <div class="form-group">
                    <label>Название</label>
                    <input name="title" type="text" class="form-control" placeholder="Title" value="<?=$currentArticle[0]['title']?>">
                </div>
                <div class="form-group">
                    <label>Дата</label>

                    <input name="date" type="datetime" class="form-control" placeholder="0000-00-00 00-00-00" value="<?=$currentArticle[0]['date']?>">
                </div>
                <div class="form-group">
                    <label>Содержимое статьи</label>
                    <textarea rows="30" cols="120" class="form-control" name="content" required><?=$currentArticle[0]['content']?></textarea>
                </div>
                <div class="form-group">
                    <label>Изображение</label>
                    <input name="image" type="text" class="form-control" placeholder="Image_name.jpg" value="<?=$currentArticle[0]['image']?>">
                </div>
                <div class="form-group">
                    <select class="form-control" name="id_category">
                    <?php foreach($categories as $category) { ?>
                        <option value="<?=$category['id_category']?>"><?=$category['category']?></option>
                    <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Теги</label>
                    <input name="tag" type="text" class="form-control" placeholder="#tag" value="<?=$currentTagStr?>">
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="edit">Изменить</button>
                <a href="//Locathost/Blog_Anna_Molibog/admin.php"><button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button></a>
            </div>
        </form>
